### ISSUE TITLE
Can't undo blacklisted tags

### ISSUE THREAD

**Issue by turquoiseteen** [darthkrallt/AO3rdr#18]
AO3rdr for Chrome is amazing, and I've blacklisted so many things. Unfortunately, as I have discovered new shows, I can't delete the previously blacklisted tag so it'll show up when I search. I can click the delete button and the tag will go away, but as soon as I refresh the page, it's there again. I'm not sure if I'm missing a "save changes" button or something, but I thought I'd mention this issue and see if you had any insight. Thanks for all your work =)

**Comment by darthkrallt** [comment]
Thank you so much for wiring in with this! I will take a look at this bug this weekend and see if I can't find a fix. :)

**Comment by turquoiseteen** [comment]
awesome! thanks so much =)
