### ISSUE TITLE
location of icons different between Chrome and Firefox

### ISSUE THREAD

**Issue by clach04** [darthkrallt/AO3rdr#2]
AO3rdr version 1.0.5

rating icons located in different places between desktop versions of Firefox:
![image](https://cloud.githubusercontent.com/assets/424032/8537135/4fb14784-240f-11e5-8198-486103b6fe12.png)

and Chrome:

![image](https://cloud.githubusercontent.com/assets/424032/8537130/3c18b054-240f-11e5-8ec4-a5d4ae67ca18.png)

Chrome version seems nicer :-)

**Comment by darthkrallt** [comment]
Codebases have converged.
