### ISSUE TITLE
Update for Firefox Quantum?

### ISSUE THREAD

**Issue by denisenadal** [darthkrallt/AO3rdr#58]
the AO3rdr add-on for Firefox doesn't work with the latest version (57).  Any chance you'll be updating for the new version?

I absolutely love this plugin, it's simple, lightweight and easy to use. It's made finding fics on AO3 so much easier and more enjoyable.  Thank you for developing this!

**Comment by darthkrallt** [comment]
Yes, I am so sorry to make you all wait. I actually had this ready about a month ago, but then got sidetracked with life. It's been submitted to firefox, just waiting on reviews now.

**Comment by darthkrallt** [comment]
Wow, they're fast at approval now. New version should be live. FYI if you don't have a copy of your cloud sync key there are recovery instructions in the "cloud sync settings".
