### ISSUE TITLE
Clarification question

### ISSUE THREAD

**Issue by Heidi8** [darthkrallt/AO3rdr#8]
Hi DarthKrallt - can you please add the word "official" into the title and description/summary, and if possible into the ReadMe file, so people are aware that this app is not an official AO3 project? We've occasionally had issues where people assume anything with AO3 on it is something the org has created, and your inclusion of "unofficial" (or "unauthorized", if you prefer) cuts down on the support requests we get, and lets people know who to credit and thank. 
Please let me know if you have any questions!

**Comment by darthkrallt** [comment]
Absolutely! Thanks for the feedback, I really appreciate it.

I hadn't realized anyone other than myself was using it- but I got 6 asks on tumblr, and this issue in the last 24 hours. If I might ask- where did you find out about this?

**Comment by darthkrallt** [comment]
I've update the readme, and description in the chrome and FF extension stores.

**Comment by Heidi8** [comment]
I believe someone sent an Ask about it to someone on my committee at AO3.
Thanks for adding in the language; it's greatly appreciated.
